### ISSUE TITLE
Add menu icon to home landing page

### ISSUE THREAD

**Issue by mikepmunroe** [greenfieldhq/greenfield#2]
Something similar to the following should be added to our view that users land on when visiting greenfieldhq.com

![quadris_-_flat_app_landing_page_-_live_preview_-_wrapbootstrap](https://cloud.githubusercontent.com/assets/514063/2551855/fde9b37c-b692-11e3-9b1b-841a142f5769.png)

**Comment by rtremaine** [comment]
Added it to the upper right corner of the splash page
